name: firebase-deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build jekyll
    - uses:  lemonarc/jekyll-action@1.0.0

    - name: npm install, firebase deploy
      run: |
        npm ci
        npm install
        ./node_modules/.bin/firebase deploy --project dionricky-blog --debug --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"