name: unpublish-blog
on:
  repository_dispatch:
    types: [google.storage.object.delete]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    # Move deleted post to _drafts
    - name: Create local changes
      run: |
        mv "./_posts/${{ github.event.client_payload.file.name }}" "./_drafts/"

    - name: Commit files
      run: |
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Unpublish post" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}